###

GET http://localhost:5056

###

POST http://localhost:5056/api/catagories
Content-Type: application/json

{
  "name":"Smartphone & electronics",
  "description":"This is description."
}

###

GET http://localhost:5056/api/catagories?searchValue=electronics
###

PUT http://localhost:5056/api/catagories/ee36dc1c-4496-4ca9-8c4c-7b82de9c113a
Content-Type: application/json

{
  "name":"Clothing 2",
  "description":"Bad Catagory."
}

###

DELETE http://localhost:5056/api/catagories/a5631e6d-dd19-4977-8848-64570bf2862b


