###

GET http://localhost:5056

###

POST http://localhost:5056/api/catagories
Content-Type: application/json

{
  "name":"Clothing",
  "description":"This is description."
}

###

GET http://localhost:5056/api/catagories

###

PUT http://localhost:5056/api/catagories/0fdfaabd-515d-47c1-9597-7125c4858b46
Content-Type: application/json

{
  "name":"Clothing 2",
  "description":"Bad Catagory."
}

###

DELETE http://localhost:5056/api/catagories/82555dc9-eec0-404f-a655-07a25985b1bd


